from datetime import datetime
from html import escape
from pathlib import Path
from typing import Optional

from scanner.engine import HostResult, ScanConfig, PortStatus


class ReportGenerator:
    def __init__(self, results: list[HostResult], scan_config: ScanConfig) -> None:
        self.results = results
        self.config = scan_config
        self.timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    def _count_open(self) -> int:
        return sum(len(h.open_ports) for h in self.results)

    def generate_html(self, output_path: str | Path) -> None:
        total_ports = len(self.config.ports) * len(self.config.targets)
        open_count = self._count_open()
        hosts_up = sum(1 for h in self.results if h.status == "up")

        parts: list[str] = []
        parts.append("<!DOCTYPE html>\n<html lang=\"zh-CN\">\n<head>")
        parts.append('<meta charset="utf-8">')
        parts.append(f"<title>Port Scan Report — {self.timestamp}</title>")
        parts.append("<style>")
        parts.append(
            "body{font-family:Arial,sans-serif;max-width:960px;margin:0 auto;padding:20px;"
            "color:#333}"
            "h1{border-bottom:2px solid #2E75B6;padding-bottom:8px}"
            "h2{color:#2E75B6;margin-top:24px}"
            "table{border-collapse:collapse;width:100%;margin:12px 0}"
            "th,td{border:1px solid #ccc;padding:6px 12px;text-align:left}"
            "th{background:#2E75B6;color:#fff}"
            "tr:nth-child(even){background:#f5f5f5}"
            ".summary-table td:first-child{font-weight:bold;width:30%}"
            ".up{color:#1a7a1a;font-weight:bold}"
            ".down{color:#c00;font-weight:bold}"
            ".open{color:#1a7a1a}"
            ".footer{margin-top:40px;color:#999;font-size:0.9em;border-top:1px solid #eee;padding-top:12px}"
        )
        parts.append("</style>\n</head>\n<body>")

        parts.append(f"<h1>Port Scan Report</h1>")
        parts.append(f"<p>Generated: {escape(self.timestamp)}</p>")

        parts.append("<h2>Summary</h2>")
        parts.append('<table class="summary-table">')
        parts.append(f"<tr><td>Target Hosts</td><td>{len(self.config.targets)}</td></tr>")
        parts.append(f"<tr><td>Ports per Host</td><td>{len(self.config.ports)}</td></tr>")
        parts.append(f"<tr><td>Total Ports Scanned</td><td>{total_ports}</td></tr>")
        parts.append(f"<tr><td>Hosts Up</td><td>{hosts_up}</td></tr>")
        parts.append(f"<tr><td>Open Ports Found</td><td>{open_count}</td></tr>")
        total_time = sum(h.scan_time for h in self.results)
        parts.append(f"<tr><td>Total Scan Time</td><td>{total_time:.2f}s</td></tr>")
        parts.append("</table>")

        if not self.results:
            parts.append("<p>No hosts scanned.</p>")
        else:
            for host in self.results:
                cls = "up" if host.status == "up" else "down"
                parts.append(f"<h2>Host: {escape(host.host)} <span class=\"{cls}\">{host.status.value.upper()}</span></h2>")
                if host.error_message:
                    parts.append(f"<p>Error: {escape(host.error_message)}</p>")
                if host.open_ports:
                    parts.append("<table><tr><th>Port</th><th>Status</th><th>Service</th></tr>")
                    for r in host.open_ports:
                        parts.append(
                            f"<tr><td>{r.port}</td>"
                            f"<td class=\"open\">{r.status.value}</td>"
                            f"<td>{escape(r.service)}</td></tr>"
                        )
                    parts.append("</table>")
                else:
                    parts.append("<p>No open ports found.</p>")

        parts.append(f'<div class="footer">Generated by Port Scanner on {escape(self.timestamp)}</div>')
        parts.append("</body>\n</html>")

        with open(output_path, "w", encoding="utf-8") as f:
            f.write("\n".join(parts))

    def generate_markdown(self, output_path: str | Path) -> None:
        open_count = self._count_open()
        hosts_up = sum(1 for h in self.results if h.status == "up")

        lines: list[str] = []
        lines.append(f"# Port Scan Report")
        lines.append(f"")
        lines.append(f"**Generated**: {self.timestamp}")
        lines.append(f"")

        lines.append("## Summary")
        lines.append("")
        lines.append(f"| Metric | Value |")
        lines.append(f"|--------|-------|")
        lines.append(f"| Target Hosts | {len(self.config.targets)} |")
        lines.append(f"| Ports per Host | {len(self.config.ports)} |")
        lines.append(f"| Hosts Up | {hosts_up} |")
        lines.append(f"| Open Ports Found | {open_count} |")
        total_time = sum(h.scan_time for h in self.results)
        lines.append(f"| Total Scan Time | {total_time:.2f}s |")
        lines.append("")

        for host in self.results:
            lines.append(f"## Host: {host.host} ({host.status.value.upper()})")
            lines.append("")
            if host.error_message:
                lines.append(f"*Error: {host.error_message}*")
                lines.append("")
            if host.open_ports:
                lines.append("| Port | Status | Service |")
                lines.append("|------|--------|---------|")
                for r in host.open_ports:
                    lines.append(f"| {r.port} | {r.status.value} | {r.service} |")
                lines.append("")
            else:
                lines.append("No open ports found.")
                lines.append("")

        with open(output_path, "w", encoding="utf-8") as f:
            f.write("\n".join(lines))
